"""
Market Intelligence - Report Builder
Generates human-readable intelligence reports
"""

import sys
from pathlib import Path

agent_os_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(agent_os_root))

from datetime import datetime
from products.shared.reports.report_gen import ReportGenerator

class MarketReportBuilder:
    def __init__(self):
        self.report_gen = ReportGenerator()

    def build_daily_report(self, scored_trends, format="text"):
        """Build a daily intelligence report"""
        date = datetime.now().strftime("%Y-%m-%d")
        top_trend, top_score = scored_trends[0] if scored_trends else ("None", 0)

        if format == "text":
            report = f"""
=== C6 Market Intelligence Report ===
Date: {date}

TOP OPPORTUNITY
  Trend: {top_trend}
  Score: {top_score}/100
  Action: Create content about {top_trend} today

OTHER TRENDS
"""
            for trend, score in scored_trends[1:5]:
                report += f"  {score:3d} - {trend}\n"

            report += f"""
Generated by: C6 AI Agent
Next report: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
            return report

        elif format == "json":
            return {
                "date": date,
                "top_trend": {"name": top_trend, "score": top_score},
                "trends": [{"name": t, "score": s} for t, s in scored_trends[:10]],
                "generated_by": "C6 Market Intelligence",
                "generated_at": datetime.now().isoformat()
            }

    def save_report(self, scored_trends, format="json"):
        """Save report to disk"""
        if format == "json":
            report_data = self.build_daily_report(scored_trends, format="json")
            return self.report_gen.save_report(report_data, "market_intelligence_daily")
        else:
            report_text = self.build_daily_report(scored_trends, format="text")
            report_path = Path(__file__).parent / "reports" / f"daily_report_{datetime.now().strftime('%Y%m%d')}.txt"
            with open(report_path, 'w') as f:
                f.write(report_text)
            return report_path

if __name__ == "__main__":
    from scanner import MarketScanner
    scanner = MarketScanner()
    trends = scanner.scan()
    builder = MarketReportBuilder()
    print(builder.build_daily_report(trends, format="text"))
